In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
for i in range (1,11):
    print(i)
    

1
2
3
4
5
6
7
8
9
10


In [3]:
import numpy as np

In [7]:
arr = np.array([1,2,3])

In [8]:
type(arr)

numpy.ndarray

In [4]:
b= np.array([[1,2,3],[4,5,6]])

In [10]:
l=[1,2,3]

In [11]:
print(l+4)

TypeError: can only concatenate list (not "int") to list

In [12]:
l=np.array([1,2,3])
print(l+4)

[5 6 7]


In [13]:
l*4

array([ 4,  8, 12])

In [14]:
l.shape

(3,)

In [5]:
b.ndim

2

In [6]:
a=np.array([1,2,3.5])

In [7]:
a


array([1. , 2. , 3.5])

In [8]:
type(a[0])

numpy.float64

In [10]:
b=np.array([4,5,6.5])
a+b

array([ 5.,  7., 10.])

In [11]:
#only same length arrays can be added

In [13]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.full((5,5),7,dtype=int)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [17]:
np.random.random((3,2))

array([[0.99678984, 0.17859416],
       [0.13078973, 0.35497853],
       [0.20733731, 0.96168064]])

In [18]:
np.random.randint(1,117)

8

In [20]:
np.random.randint(1,117,size=(3,3))

array([[27, 17, 22],
       [10, 76, 31],
       [97, 77, 32]])

In [23]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [24]:
np.arange(2,11,2.5)

array([2. , 4.5, 7. , 9.5])

In [25]:
a=np.arange(1,11)

In [26]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
[ 1,  2,  3,  4,  -5,  -6, - 7,  8,  9, 10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Boolean Index

In [29]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
a[(a>4) & (a<8)]*=-1
a

array([ 1,  2,  3,  4, -5, -6, -7,  8,  9, 10])

In [37]:
np.mean(a)

1.9

In [38]:
np.median(a)

2.5

In [40]:
np.std(a)

5.906775770248943

In [41]:
b=np.arange(1,21)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
b=b.reshape((5,4))

In [46]:
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [47]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
b.max(axis=0) #coulmn wise max values

array([17, 18, 19, 20])

In [50]:
b.max(axis=1) #row wise max values

array([ 4,  8, 12, 16, 20])

In [51]:
b.min(axis=1)

array([ 1,  5,  9, 13, 17])